In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split , cross_val_score
from matplotlib import pyplot as plt

In [2]:
df = pd.read_csv("./house-prices-advanced-regression-techniques/train.csv")
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [3]:
cols=df.columns.tolist()
print(cols)

['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType', 'SaleCondition', 'SalePrice']

In [4]:
features = ["Id","MSSubClass","LotArea","OverallQual","OverallCond","YearBuilt","YearRemodAdd","1stFlrSF",'2ndFlrSF','LowQualFinSF',
            'GrLivArea',"FullBath","HalfBath","BedroomAbvGr","KitchenAbvGr","TotRmsAbvGrd","Fireplaces","WoodDeckSF","OpenPorchSF",
            "EnclosedPorch","3SsnPorch","ScreenPorch","PoolArea","MiscVal","MoSold","YrSold"]

df[features]

,Id,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,1stFlrSF,2ndFlrSF,LowQualFinSF,...,Fireplaces,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,1,60,8450,7,5,2003,2003,856,854,0,...,0,0,61,0,0,0,0,0,2,2008
1,2,20,9600,6,8,1976,1976,1262,0,0,...,1,298,0,0,0,0,0,0,5,2007
2,3,60,11250,7,5,2001,2002,920,866,0,...,1,0,42,0,0,0,0,0,9,2008
3,4,70,9550,7,5,1915,1970,961,756,0,...,1,0,35,272,0,0,0,0,2,2006
4,5,60,14260,8,5,2000,2000,1145,1053,0,...,1,192,84,0,0,0,0,0,12,2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,7917,6,5,1999,2000,953,694,0,...,1,0,40,0,0,0,0,0,8,2007
1456,1457,20,13175,6,6,1978,1988,2073,0,0,...,2,349,0,0,0,0,0,0,2,2010
1457,1458,70,9042,7,9,1941,2006,1188,1152,0,...,2,0,60,0,0,0,0,2500,5,2010
1458,1459,20,9717,5,6,1950,1996,1078,0,0,...,0,366,0,112,0,0,0,0,4,2010
1459,1460,20,9937,5,6,1965,1965,1256,0,0,...,0,736,68,0,0,0,0,0,6,2008

In [5]:
x = df[features]
y = df["SalePrice"]

#%% train/test split and normlization of data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [6]:
from sklearn.preprocessing import MinMaxScaler
# scaling the input data
scaler_x = MinMaxScaler()
scaler_x.fit(x_train)
scaled_x_train=scaler_x.transform(x_train)
scaled_x_test = scaler_x.transform(x_test)

# scaling the output data
scaler_y=MinMaxScaler()
scaler_y.fit(y_train.values.reshape(-1, 1))
scaled_y_train=scaler_y.transform(y_train.values.reshape(-1, 1))
scaled_y_train=scaled_y_train.ravel()
scaled_y_test = scaler_y.transform(y_test.values.reshape(-1, 1))
scaled_y_test=scaled_y_test.ravel()

In [ ]:
#%% Training the random forest model using RandomizedSearchCV for optimization of parameters
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV

# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
           'max_features': max_features,
           'max_depth': max_depth,
           'min_samples_split': min_samples_split,
           'min_samples_leaf': min_samples_leaf,
           'bootstrap': bootstrap}

# Model
rf = RandomForestRegressor() #n_estimators = 1000, random_state = 42
model = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 100, cv = 10, verbose=2, random_state=42, n_jobs = -1)
model.fit(scaled_x_train, scaled_y_train)

Fitting 10 folds for each of 100 candidates, totalling 1000 fits

In [ ]:
print(model.score(scaled_x_test,scaled_y_test))

In [ ]:
test_data = pd.read_csv("./house-prices-advanced-regression-techniques/test.csv")
test_data

In [ ]:
test_data_features = test_data[features]
test_data_features

In [ ]:
target_scaled=model.predict(test_data_features)
target=scaler_y.inverse_transform(target_scaled.reshape(-1,1))
output = pd.DataFrame({"Id":test_data["Id"],"SalePrice":target})
output.to_csv("house_prediction_submission.csv",index=False)
print("done")